[2022-06-11 11:14:02,395] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 11:14:02,396] [builder.py:185]            [INFO]     |                               Country Collections Collection in 亚洲电影                               |
[2022-06-11 11:14:02,397] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 11:14:02,398] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 11:14:02,405] [builder.py:191]            [INFO]     |============================ Validating Country Collections Attributes =============================|
[2022-06-11 11:14:02,407] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 11:14:02,408] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 11:14:02,411] [meta.py:103]               [DEBUG]    | Value: [ordereddict([('name', 'separator'), ('separator', 'country')])]                            |
[2022-06-11 11:14:02,418] [builder.py:430]            [DEBUG]    |                                                                                                    |
[2022-06-11 11:14:02,418] [builder.py:431]            [DEBUG]    | Validating Method: blank_collection                                                                |
[2022-06-11 11:14:02,419] [builder.py:432]            [DEBUG]    | Value: True                                                                                        |
[2022-06-11 11:14:02,420] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 11:14:02,421] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 11:14:02,422] [builder.py:605]            [DEBUG]    | Value: !09_!Country Collections                                                                    |
[2022-06-11 11:14:02,423] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 11:14:02,424] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 11:14:02,425] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/separators/country.jpg |
[2022-06-11 11:14:03,034] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-11 11:14:03,035] [plex.py:745]               [DEBUG]    | Looking for: Country Collections                                                                   |
[2022-06-11 11:14:03,036] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 11:14:03,036] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 11:14:03,037] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 11:14:03,037] [plex_meta_manager.py:541]  [INFO]     |============================== Running Country Collections Collection ==============================|
[2022-06-11 11:14:06,604] [builder.py:2383]           [INFO]     |                                                                                                    |
[2022-06-11 11:14:06,605] [builder.py:2384]           [INFO]     |======================== Updating Details of Country Collections Collection ========================|
[2022-06-11 11:14:06,606] [builder.py:2385]           [INFO]     |                                                                                                    |
[2022-06-11 11:14:06,606] [builder.py:2446]           [INFO]     | Collection Metadata Edits                                                                          |
                                                                 | Sort Title | !09_!Country Collections
[2022-06-11 11:14:33,909] [builder.py:2450]           [INFO]     | Details: have been updated
[2022-06-11 11:14:33,910] [builder.py:2454]           [INFO]     | 
[2022-06-11 11:14:33,910] [util.py:150]               [DEBUG]    | 1 poster found:
[2022-06-11 11:14:33,911] [util.py:152]               [DEBUG]    | Method: url_poster Poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/separators/country.jpg
[2022-06-11 11:14:37,885] [library.py:153]            [INFO]     | Detail: url_poster updated poster to [URL] https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/separators/country.jpg
[2022-06-11 11:15:39,998] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 646, in run_collection
                                                                 |     builder.send_notifications()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2607, in send_notifications
                                                                 |     if self.obj and self.details["changes_webhooks"] and \
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/collection.py", line 110, in __len__
                                                                 |     return len(self.items())
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/collection.py", line 193, in items
                                                                 |     items = self.fetchItems(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 267, in fetchItems
                                                                 |     data = self._server.query(ekey, params=url_kw)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 11:15:40,223] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 11:15:40,226] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 11:15:40,227] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 11:15:40,228] [plex_meta_manager.py:675]  [INFO]     |                              Finished Country Collections Collection                               |
[2022-06-11 11:15:40,229] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:37                                    |
[2022-06-11 11:15:40,244] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
