[2022-06-11 10:41:48,097] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:41:48,099] [builder.py:185]            [INFO]     |                                TMDb Top Rated Collection in Movies                                 |
[2022-06-11 10:41:48,099] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:41:48,100] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 10:41:48,100] [builder.py:191]            [INFO]     |=============================== Validating TMDb Top Rated Attributes ===============================|
[2022-06-11 10:41:48,101] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,102] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 10:41:48,103] [meta.py:103]               [DEBUG]    | Value: [ordereddict([('name', 'top')]), ordereddict([('name', 'customsync')]), ordereddict([('name', 'chart_shared'), ('key', 'top')])] |
[2022-06-11 10:41:48,112] [builder.py:437]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,113] [builder.py:438]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-06-11 10:41:48,113] [builder.py:442]            [DEBUG]    | Value: sync                                                                                        |
[2022-06-11 10:41:48,114] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,114] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-11 10:41:48,115] [builder.py:584]            [DEBUG]    | Value: custom                                                                                      |
[2022-06-11 10:41:48,115] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,116] [builder.py:604]            [DEBUG]    | Validating Method: tmdb_top_rated                                                                  |
[2022-06-11 10:41:48,117] [builder.py:605]            [DEBUG]    | Value: 100                                                                                         |
[2022-06-11 10:41:48,118] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,119] [builder.py:604]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-06-11 10:41:48,120] [builder.py:605]            [DEBUG]    | Value: A collection of the top rated movies according to TMDb.                                     |
[2022-06-11 10:41:48,120] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,121] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 10:41:48,122] [builder.py:605]            [DEBUG]    | Value: !01_TMDb Top Rated                                                                          |
[2022-06-11 10:41:48,122] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:41:48,123] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 10:41:48,124] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/TMDb%20Top%20Rated.jpg |
[2022-06-11 10:42:50,152] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 537, in run_collection
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str)
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 752, in __init__
                                                                 |     if self.obj:
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/collection.py", line 110, in __len__
                                                                 |     return len(self.items())
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/collection.py", line 193, in items
                                                                 |     items = self.fetchItems(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 267, in fetchItems
                                                                 |     data = self._server.query(ekey, params=url_kw)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 10:42:50,365] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 10:42:50,366] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 10:42:50,366] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 10:42:50,367] [plex_meta_manager.py:675]  [INFO]     |                                 Finished TMDb Top Rated Collection                                 |
[2022-06-11 10:42:50,367] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:02                                    |
[2022-06-11 10:42:50,368] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
